version: '3.8'
services:
   webapp:
    build: .
    container_name: herejesSazonApp
    ports:
      - "8080:8080"
    volumes:
      - .:/webapp #bindmount local y contenedor
      - ./migrations:/migrations #facilitarle la ruta al .sh
    environment:
      - DATABASE_HOST=host.docker.internal
      - DATABASE_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB:-HerejesSazonBD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - app_network

networks:
  app_network:
   driver: bridge