version: '3.8'
services:
   BD:
      image: postgres:17
      container_name: BD_herejesSazon
      restart: always
      volumes:
         - postgre_data:/var/lib/postgresql/data
         - ./backups:/backups
      ports:
         - "5432:5432"
      environment:
         - DATABASE_HOST=${DATABASE_HOST}
         - POSTGRES_USER=${POSTGRES_USER}
         - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
         - POSTGRES_DB=HerejesSazonBD
      healthcheck:
         test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d HerejesSazonBD"]
         interval: 10s
         timeout: 5s
         retries: 5
         start_period: 30s
      networks: 
         - app_network


   webapp:
    build: .
    container_name: herejesSazonApp
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-HerejesSazonBD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      BD:
         condition: service_healthy
    networks:
      - app_network

volumes:
   postgre_data:

networks:
  app_network:
   driver: bridge